#List of diseases
import pickle

list_diseaseNames =['Abscess',
'Alzheimer'	,
'Anotia'	,
'Anthrax'	,
'Appendicitis'	,
'Apraxia'	,
'Argyria'	,
'Arthritis'	,
'Aseptic meningitis'	,
'Asthenia'	,
'Asthma'	,
'Astigmatism'	,
'Atherosclerosis'	,
'Athetosis'	,
'Atrophy'	,
'Bacterial meningitis'	,
'Beriberi'	,
'Black Death'	,
'Botulism'	,
'Breast cancer'	,
'Bronchitis'	,
'Brucellosis'	,
'Bubonic plague'	,
'Bunion'	,
'Calculi'	,
'Campylobacter infection'	,
'Cancer'	,
'Candidiasis'	,
'Carbon monoxide poisoning'	,
'Celiacs disease'	,
'Cerebral palsy'	,
'Chagas disease'	,
'Chalazion'	,
'Chancroid'	,
'Chavia'	,
'Congenital insensitivity to pain with anhidrosis'	,
'Cherubism'	,
'Chickenpox'	,
'Chlamydia'	,
'Chlamydia trachomatis'	,
'Cholera'	,
'Chordoma'	,
'Chorea'	,
'Chronic fatigue syndrome'	,
'Circadian rhythm sleep disorder'	,
'Coccidioidomycosis'	,
'Colitis'	,
'Common cold'	,
'Condyloma'	,
'Congestive heart disease'	,
'Coronary heart disease'	,
'Cowpox'	,
'Cretinism'	,
'Dengue'	,
'Diabetes mellitus'	,
'Diphtheria'	,
'Dehydration'	,
'Dysentery'	,
'Ear infection'	,
'Ebola'	,
'Encephalitis'	,
'Emphysema'	,
'Epilepsy'	,
'Erectile dysfunctions'	,
'Fibromyalgia'	,
'flu'	,
'Gangrene'	,
'Gastroenteritis'	,
'Genital herpes'	,
'GERD'	,
'Goitre'	,
'Gonorrhea'	,
'Heart disease'	,
'Hepatitis A'	,
'Hepatitis B'	,
'Hepatitis C'	,
'Hepatitis D'	,
'Hepatitis E'	,
'HIV'	,
'Human papillomavirus'	,
'Hypermetropia'	,
'Hyperopia'	,
'Hyperthyroidism'	,
'Hypothyroid'	,
'Hypotonia'	,
'Impetigo'	,
'Infertility'	,
'Influenza'	,
'Interstitial cystitis'	,
'Iritis'	,
'Iron-deficiency anemia'	,
'Irritable bowel syndrome'	,
'Ignious Syndrome'	,
'Jaundice'	,
'Keloids'	,
'Kuru'	,
'Kwashiorkor'	,
'Kidney stone disease'	,
'Laryngitis'	,
'Lead poisoning'	,
'Legionellosis'	,
'Leishmaniasis'	,
'Leprosy'	,
'Leptospirosis'	,
'Listeriosis'	,
'Leukemia'	,
'Lice'	,
'Loiasis'	,
'Lung cancer'	,
'Lupus erythematosus'	,
'Lyme disease'	,
'Lymphogranuloma venereum'	,
'Lymphoma'	,
'Limbtoosa'	,
'Mad cow disease'	,
'Malaria'	,
'Marburg fever'	,
'Measles'	,
'Melanoma'	,
'Metastatic cancer'	,
'Meningitis'	,
'Migraine'	,
'Mononucleosis'	,
'Multiple myeloma'	,
'Multiple sclerosis'	,
'Mumps'	,
'Muscular dystrophy'	,
'Myasthenia gravis'	,
'Myelitis'	,
'Myoclonus'	,
'Myopia'	,
'Myxedema'	,
'Morquio Syndrome'	,
'Mattticular syndrome'	,
'Mononucleosis'	,
'Neoplasm'	,
'Non-gonococcal urethritis'	,
'Necrotizing Fasciitis'	,
'Night blindness'	,
'Obesity'	,
'Osteoarthritis'	,
'Osteoporosis'	,
'Otitis'	,
'Palindromic rheumatism'	,
'Paratyphoid fever'	,
'Pelvic inflammatory disease'	,
'Peritonitis'	,
'Periodontal disease'	,
'Pertussis'	,
'Plague'	,
'Poliomyelitis'	,
'Porphyria'	,
'Progeria'	,
'Prostatitis'	,
'Psittacosis'	,
'Psoriasis'	,
'Pubic lice'	,
'Pulmonary embolism'	,
'Pilia'	,
'pneumonia'	,
'Ques fever'	,
'Rabies'	,
'Repetitive strain injury'	,
'Rheumatic fever'	,
'Rheumatic heart'	,
'Rheumatism'	,
'Rheumatoid arthritis'	,
'Rickets'	,
'Rift Valley fever'	,
'Rocky Mountain spotted fever'	,
'Rubella'	,
'Salmonellosis'	,
'Scabies'	,
'Scarlet fever'	,
'Sciatica'	,
'Scleroderma'	,
'Scrapie'	,
'Scurvy'	,
'Sepsis'	,
'Septicemia'	,
'SARS'	,
'Shigellosis'	,
'Shin splints'	,
'Shingles'	,
'Sickle-cell anemia'	,
'Siderosis'	,
'SIDS'	,
'Silicosis'	,
'Smallpox'	,
'Stevens-Johnson syndrome'	,
'Stomach flu'	,
'Stomach ulcers'	,
'Strabismus'	,
'Strep throat'	,
'Streptococcal infection'	,
'Synovitis'	,
'Syphilis'	,
'Swine influenza'	,
'Schizophrenia'	,
'Taeniasis'	,
'Tay-Sachs disease'	,
'Tennis elbow'	,
'Teratoma'	,
'Tetanus'	,
'Thalassaemia'	,
'Thrush'	,
'Thymoma'	,
'Tinnitus'	,
'Tonsillitis'	,
'Tooth decay'	,
'Toxic shock syndrome'	,
'Trichinosis'	,
'Trichomoniasis'	,
'Trisomy'	,
'Tuberculosis'	,
'Tularemia'	,
'Tungiasis'	,
'Typhoid fever'	,
'Typhus'	,
'Tumor'	,
'Ulcerative colitis'	,
'Ulcers'	,
'Uremia'	,
'Urticaria'	,
'Uveitis'	,
'Varicella'	,
'Varicose veins'	,
'Vasovagal syncope'	,
'Vitiligo'	,
'Von Hippel-Lindau disease'	,
'Viral fever'	,
'Viral meningitis'	,
'Warkany syndrome'	,
'Warts'	,
'Watkins'	,
'Yellow fever'	,
'Yersiniosis'	,

 ]


with open('list_diseaseNames.pkl', 'wb') as f:
       pickle.dump(list_diseaseNames, f) 
#       
#flist_diseaseNames = open("list_diseaseNames.pkl",'r')
#list_diseaseNames = pickle.load(flist_diseaseNames)









